name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Add Rust src
      run : rustup component add rust-src
    - name: Switch to Rust Nightly
      run : rustup override set nightly
    - name : Add Component
      run : rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
    - name : Adding Embedded ARM
      run : rustup target add thumbv7em-none-eabihf
    - name : Build for Embedded ARM
      run : cargo build --target thumbv7em-none-eabihf
    - name: Build for our x86_64
      run: cargo build --target kernel.json
