name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Switch to Rust Nightly
      run : rustup override set nightly
    - name : Adding Embedded ARM
      run : rustup target add thumbv7em-none-eabihf
    - name : Build for Embedded ARM
      run : cargo build --target thumbv7em-none-eabihf
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
